/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as QrImport } from './routes/qr'
import { Route as PayImport } from './routes/pay'
import { Route as IndexImport } from './routes/index'

// Create/Update Routes

const QrRoute = QrImport.update({
  id: '/qr',
  path: '/qr',
  getParentRoute: () => rootRoute,
} as any)

const PayRoute = PayImport.update({
  id: '/pay',
  path: '/pay',
  getParentRoute: () => rootRoute,
} as any)

const IndexRoute = IndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/solid-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/pay': {
      id: '/pay'
      path: '/pay'
      fullPath: '/pay'
      preLoaderRoute: typeof PayImport
      parentRoute: typeof rootRoute
    }
    '/qr': {
      id: '/qr'
      path: '/qr'
      fullPath: '/qr'
      preLoaderRoute: typeof QrImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/pay': typeof PayRoute
  '/qr': typeof QrRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/pay': typeof PayRoute
  '/qr': typeof QrRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexRoute
  '/pay': typeof PayRoute
  '/qr': typeof QrRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/pay' | '/qr'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/pay' | '/qr'
  id: '__root__' | '/' | '/pay' | '/qr'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  PayRoute: typeof PayRoute
  QrRoute: typeof QrRoute
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  PayRoute: PayRoute,
  QrRoute: QrRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/pay",
        "/qr"
      ]
    },
    "/": {
      "filePath": "index.tsx"
    },
    "/pay": {
      "filePath": "pay.tsx"
    },
    "/qr": {
      "filePath": "qr.tsx"
    }
  }
}
ROUTE_MANIFEST_END */
